version: '3.8'

services:
  subtrackr:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./web:/app/web
      - ./templates:/app/templates
    environment:
      - GIN_MODE=release
      - DATABASE_PATH=/app/data/subtrackr.db
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  subtrackr_data:
    driver: local